---
- name: Copy SSH private key to all instances
  hosts: bastion_host,webservers
  become: true
  gather_facts: false
  pre_tasks:
    - name: Wait for SSH to be available
      wait_for_connection:
        timeout: 120

  tasks:
    - name: Ensure .ssh directory exists
      file:
        path: /home/ubuntu/.ssh
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0700'

    - name: Copy lab_rsa.pem to ~/.ssh/
      copy:
        src: lab_rsa.pem
        dest: /home/ubuntu/.ssh/lab_rsa.pem
        owner: ubuntu
        group: ubuntu
        mode: '0600'
